import { ItemPortfolio } from "../../models/item-portfolio";

export const ITENS_PORTFOLIO: ItemPortfolio[] = [
  {
titulo: 'Controle de Bar',
      urlImagem: 'projetos/controle-de-bar.png',
      urlGif: 'https://i.imgur.com/kioD02O.gif',
      urlRepositorio: 'https://github.com/Iagodizlla/controle-de-bar',
      stack: [
        'https://skillicons.dev/icons?i=html&theme=light',
        'https://skillicons.dev/icons?i=css&theme=light',
        'https://skillicons.dev/icons?i=cs&theme=light',
        'https://skillicons.dev/icons?i=net&theme=light',
        'https://skillicons.dev/icons?i=bootstrap&theme=light',
        'https://skillicons.dev/icons?i=javascript&theme=light',
      ],
      descricao: `O sistema de Controle de Bar é um projeto que visa o gerenciamento de um bar, com o controle de estoque, funcionários, clientes e pedidos. O sistema permite a criação de pedidos, a atualização do estoque e a visualização dos dados dos clientes e funcionários.`,
    },
    {
      titulo: 'Gestão de Equipamentos',
      urlImagem: 'projetos/gestao-de-equipamentos.png',
      urlGif: 'https://i.imgur.com/kxM2Bre.gif',
      urlRepositorio: 'https://github.com/iagodizlla/gestao-de-equipamentos',
      stack: [
        'https://skillicons.dev/icons?i=html&theme=light',
        'https://skillicons.dev/icons?i=css&theme=light',
        'https://skillicons.dev/icons?i=cs&theme=light',
        'https://skillicons.dev/icons?i=net&theme=light',
      ],
      descricao: `O sistema de Gestão de Equipamentos controla o estoque de um almoxarifado, com a gestão de equipamentos e o registro de chamados de manutenção que eventualmente ocorrem durante o uso dos equipamentos. Também são inclusas informações sobre os fabricantes dos equipamentos para contato de suporte ou compras.`,
    },
    {
      titulo: 'E-Agenda',
      urlImagem: 'projetos/e-agenda.png',
      urlGif: 'https://i.imgur.com/cAuC5j0.gif',
      urlRepositorio: 'https://github.com/Iagodizlla/e-Agenda',
      stack: [
        'https://skillicons.dev/icons?i=html&theme=light',
        'https://skillicons.dev/icons?i=css&theme=light',
        'https://skillicons.dev/icons?i=cs&theme=light',
        'https://skillicons.dev/icons?i=net&theme=light',
        'https://skillicons.dev/icons?i=bootstrap&theme=light',
        'https://skillicons.dev/icons?i=javascript&theme=light',
        'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/microsoftsqlserver/microsoftsqlserver-plain.svg',
        'https://skillicons.dev/icons?i=azure&theme=light',
      ],
      descricao: `A e-Agenda é um sistema web para gerenciar tarefas, contatos, compromissos, categorias e despesas. Permite cadastrar, editar, excluir e visualizar registros, com suporte a itens de tarefa, prioridades e controle de conclusão. Ideal para organização pessoal e profissional.`,
    },
    {
      titulo: 'E-Agenda-Orm',
      urlImagem: 'projetos/e-agenda.png',
      urlGif: 'https://i.imgur.com/cAuC5j0.gif',
      urlRepositorio: 'https://github.com/Iagodizlla/e-Agenda-ORM',
      stack: [
        'https://skillicons.dev/icons?i=html&theme=light',
        'https://skillicons.dev/icons?i=css&theme=light',
        'https://skillicons.dev/icons?i=cs&theme=light',
        'https://skillicons.dev/icons?i=net&theme=light',
        'https://skillicons.dev/icons?i=bootstrap&theme=light',
        'https://skillicons.dev/icons?i=javascript&theme=light',
        'https://skillicons.dev/icons?i=postgresql&theme=light',
        'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/render.svg',
      ],
      descricao: `A e-Agenda é um sistema web para gerenciar tarefas, contatos, compromissos, categorias e despesas. Permite cadastrar, editar, excluir e visualizar registros, com suporte a itens de tarefa, prioridades e controle de conclusão. Ideal para organização pessoal e profissional.`,
    },
    {
      titulo: 'Controle de Cinema',
      urlImagem: 'projetos/controle-de-cinema.png',
      urlGif: 'https://i.imgur.com/K48XU9w.gif',
      urlRepositorio: 'https://github.com/runa-do-codigo/controle-de-cinema',
      stack: [
        'https://skillicons.dev/icons?i=html&theme=light',
        'https://skillicons.dev/icons?i=css&theme=light',
        'https://skillicons.dev/icons?i=cs&theme=light',
        'https://skillicons.dev/icons?i=net&theme=light',
        'https://skillicons.dev/icons?i=bootstrap&theme=light',
        'https://skillicons.dev/icons?i=javascript&theme=light',
        'https://skillicons.dev/icons?i=postgresql&theme=light',
        'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/render.svg',
        'https://skillicons.dev/icons?i=azure&theme=light',
        'https://skillicons.dev/icons?i=docker&theme=light',
        'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/newrelic.svg',
        'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/selenium.svg',
        'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/moq.svg',
      ],
      descricao: `O Controle de Cinema tem como objetivo gerenciar filmes, sessões e ingressos de forma prática e organizada, permitindo que empresas administrem filmes, salas e sessões, enquanto clientes podem visualizar opções, escolher lugares e comprar ingressos.`,
    },
    {
      titulo: 'Site Pessoal',
      urlImagem: 'projetos/site-pessoal.png',
      urlGif: 'https://i.imgur.com/AEdcdKF.gif',
      urlRepositorio: 'https://github.com/Iagodizlla/Site_Prototipo',
      stack: [
        'https://skillicons.dev/icons?i=html&theme=light',
        'https://skillicons.dev/icons?i=css&theme=light',
        'https://skillicons.dev/icons?i=javascript&theme=light',
      ],
      descricao: `Este é o meu site pessoal, onde compartilho informações sobre mim, meu server de Minecraft e minigames, como torneios e batalhas em equipes.`,
    },
    {
      titulo: 'Pokédex',
      urlImagem: 'projetos/pokedex.png',
      urlGif: 'https://i.imgur.com/SEU_GIF.gif',
      urlRepositorio: 'https://github.com/Iagodizlla/pokedex',
      stack: [
        'https://skillicons.dev/icons?i=html&theme=light',
        'https://skillicons.dev/icons?i=scss&theme=light',
        'https://skillicons.dev/icons?i=typescript&theme=light',
        'https://skillicons.dev/icons?i=angular&theme=light',
        'https://skillicons.dev/icons?i=nodejs&theme=light',
        'https://skillicons.dev/icons?i=bootstrap&theme=light',
        'https://cdn.simpleicons.org/prettier?viewbox=auto',
        'https://cdn.simpleicons.org/eslint/4B32C3',
        'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/rxjs/rxjs-original.svg',
      ],
      descricao: `Pokédex desenvolvida em Angular, com funcionalidades de favoritar Pokémon, exibição de detalhes como sprites, sons e tipos. Projeto com foco em consumo de API, interatividade e design responsivo.`,
    },
    {
      titulo: 'Jogo de Adivinhação',
      urlImagem: 'projetos/jogo-adivinhacao.png',
      urlGif: 'https://i.imgur.com/SEU_GIF.gif',
      urlRepositorio: 'https://github.com/Iagodizlla/jogo-de-divinhacao',
      stack: [
        'https://skillicons.dev/icons?i=html&theme=light',
        'https://skillicons.dev/icons?i=scss&theme=light',
        'https://skillicons.dev/icons?i=typescript&theme=light',
        'https://skillicons.dev/icons?i=angular&theme=light',
        'https://skillicons.dev/icons?i=nodejs&theme=light',
        'https://skillicons.dev/icons?i=bootstrap&theme=light',
      ],
      descricao: `Jogo interativo de adivinhação de números com níveis de dificuldade ajustáveis. Permite que o usuário escolha a dificuldade e mantém um ranking local por nível, oferecendo feedback em tempo real.`,
    },
    {
      titulo: 'Organiza Med',
      urlImagem: 'projetos/organiza-med.png',
      urlGif: 'https://i.imgur.com/SEU_GIF.gif',
      urlRepositorio: 'https://github.com/Iagodizlla/oraganiza-med',
      stack: [
        'https://skillicons.dev/icons?i=html&theme=light',
        'https://skillicons.dev/icons?i=scss&theme=light',
        'https://skillicons.dev/icons?i=typescript&theme=light',
        'https://skillicons.dev/icons?i=angular&theme=light',
        'https://skillicons.dev/icons?i=nodejs&theme=light',
        'https://skillicons.dev/icons?i=cs&theme=light',
        'https://skillicons.dev/icons?i=net&theme=light',
        'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/rxjs/rxjs-original.svg',
        'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/newrelic.svg',
        'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/microsoftsqlserver/microsoftsqlserver-plain.svg',
      ],
      descricao: `O Organiza Med é um sistema web para gerenciamento de consultas médicas, permitindo agendamento, cancelamento e visualização de consultas. Ideal para clínicas e consultórios otimizarem o atendimento aos pacientes.`,
    },
    {
      titulo: 'Note Keeper',
      urlImagem: 'projetos/note-keeper.png',
      urlGif: 'https://i.imgur.com/SEU_GIF.gif',
      urlRepositorio: 'https://github.com/Iagodizlla/note-keeper',
      stack: [
        'https://skillicons.dev/icons?i=html&theme=light',
        'https://skillicons.dev/icons?i=scss&theme=light',
        'https://skillicons.dev/icons?i=typescript&theme=light',
        'https://skillicons.dev/icons?i=angular&theme=light',
        'https://skillicons.dev/icons?i=nodejs&theme=light',
        'https://skillicons.dev/icons?i=bootstrap&theme=light',
        'https://skillicons.dev/icons?i=cs&theme=light',
        'https://skillicons.dev/icons?i=net&theme=light',
        'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/rxjs/rxjs-original.svg',
        'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/newrelic.svg',
        'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/microsoftsqlserver/microsoftsqlserver-plain.svg',
         'https://skillicons.dev/icons?i=azure&theme=light',
      ],
      descricao: `O Note Keeper é um sistema web para criação, edição e organização de notas. Permite gerenciar anotações de forma simples e rápida, com CRUD completo integrado entre Angular e C#. Ideal para registrar e consultar informações do dia a dia.`,
    },{
      titulo: 'Academia do Zé',
      urlImagem: 'projetos/em-desenvolvimento.png',
      urlGif: 'https://i.imgur.com/SEU_GIF.gif',
      urlRepositorio: 'https://github.com/Iagodizlla/AcademiaZe',
      stack: [
        'https://skillicons.dev/icons?i=cs&theme=light',
        'https://skillicons.dev/icons?i=net&theme=light',
        'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg',
        'https://skillicons.dev/icons?i=docker&theme=light',
      ],
      descricao: `O sistema Academia do Zé é uma aplicação para gerenciar as operações de uma academia, incluindo cadastro de alunos, controle de mensalidades, agendamento de aulas e gerenciamento de instrutores. Projetado para otimizar a administração e melhorar a experiência dos clientes.`,
    },
];
